### ISSUE TITLE
Incorrect hash data - compared to no-intro

### ISSUE THREAD

**Issue by rwebster85** [HTV04/MMLC-Extractor#2]
Hi mate,

The hash data of the roms doesn't match the no-intro page of the Legacy Collection version. Could it be because being in the UK that Capcom might be shipping the PAL version of the game? Below is for the first one.

No-intro page: https://datomatic.no-intro.org/index.php?page=show_record&s=45&n=2847

SHA-1: 63E8A6E3A443BC7FC27E939FF59C7B160046392E

My SHA-1 extracted: 4788DEFA4609A20BB794E3236138D5508A9A78FE

**Comment by rwebster85** [comment]
Update on this. I thought I'd have a mess around.

I used NES Mapper to remove the header of the exported ROM file, which made all the hash data match the no-intro for the LC dump. Then using the Online ROM Patcher on romhacking.net (https://www.romhacking.net/patch/) I added the new ROM, ticked "Add Temporary Header" and selected your Mega Man (Original).ips file.

The resulting file is a clean USA ROM with hash data that matches https://datomatic.no-intro.org/index.php?page=show_record&s=45&n=1396

**Comment by HTV04** [comment]
Hey, sorry for not seeing this earlier. No-Intro doesn't include the iNES headers for NES games when calculating the hash (because it isn't part of the ROM, it's added to it to help emulators identify what to emulate), so yeah, that's probably what threw the hash off.
